"""
Auto-generated MIL test for ACC-REQ-002
Generated by: src/genai/test_generator_mil.py
"""
import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).resolve().parents[2]))

import numpy as np
from src.models.acc_controller import ACCController
from src.models.plant_model import PlantModel
from src.utils.signal_metrics import evaluate_oracle

def run_acc_req_002(dtype='float64') -> dict:
    # Simulation parameters
    sample_time = 0.1
    duration = 15.0
    steps = int(duration / sample_time) + 1

    # Stimulus parameters
    v_set = 30.0                     # desired ego speed (m/s)
    v_lead_initial = 30.0            # lead initial speed (m/s)
    v_lead_final = 15.0              # lead final speed (m/s)
    lead_decel = -3.0                # lead deceleration (m/s^2)
    event_time = 2.0                 # time when lead starts decelerating (s)
    d_initial = 45.0                 # initial distance (m)

    # Initial states
    v_ego = v_set
    d_actual = d_initial

    # Instantiate models
    acc = ACCController(sample_time, dtype=dtype)
    plant = PlantModel(sample_time)

    # Containers for signals
    time_list = []
    v_ego_list = []
    v_lead_list = []
    d_actual_list = []
    a_cmd_list = []
    mode_list = []
    d_safe_list = []

    for i in range(steps):
        t = i * sample_time

        # Lead vehicle speed profile
        if t >= event_time:
            v_lead = max(v_lead_final,
                         v_lead_initial + lead_decel * (t - event_time))
        else:
            v_lead = v_lead_initial

        # ACC controller computes command
        a_cmd, mode = acc.step(v_ego, v_lead, d_actual, v_set)

        # Plant updates ego state (and returns updated lead speed, ignored here)
        v_ego, x_ego, d_actual, _ = plant.step(a_cmd, v_lead)

        # Simple safe distance model (time gap 1.5 s + 2 m stand‑still buffer)
        d_safe = v_ego * 1.5 + 2.0

        # Record signals
        time_list.append(t)
        v_ego_list.append(float(v_ego))
        v_lead_list.append(float(v_lead))
        d_actual_list.append(float(d_actual))
        a_cmd_list.append(float(a_cmd))
        # mode may be enum/int/array; store as int if possible
        try:
            mode_val = int(mode)
        except Exception:
            mode_val = mode
        mode_list.append(mode_val)
        d_safe_list.append(float(d_safe))

    signals = {
        'time': time_list,
        'v_ego': v_ego_list,
        'v_lead': v_lead_list,
        'd_actual': d_actual_list,
        'a_cmd': a_cmd_list,
        'mode': mode_list,
        'd_safe': d_safe_list,
    }

    oracle = {
        'type': 'lower_bound',
        'signal': 'd_actual',
        'evaluation_window_s': [5.0, 15.0],
        'reference_signal': 'd_safe',
    }

    passed = evaluate_oracle(oracle, signals)

    details = (
        f"Requirement ACC-REQ-002 {'passed' if passed else 'failed'}: "
        f"d_actual {'≥' if passed else '<'} d_safe over the evaluation window (5‑15 s)."
    )

    return {
        'requirement_id': 'ACC-REQ-002',
        'passed': passed,
        'signals': signals,
        'details': details,
    }