"""
Auto-generated MIL test for ACC-REQ-003
Generated by: src/genai/test_generator_mil.py
"""
import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).resolve().parents[2]))

import numpy as np
from src.models.acc_controller import ACCController
from src.models.plant_model import PlantModel
from src.utils.signal_metrics import evaluate_oracle

def run_acc_req_003(dtype='float64') -> dict:
    import numpy as np
    from src.models.acc_controller import ACCController
    from src.models.plant_model import PlantModel
    from src.utils.signal_metrics import evaluate_oracle

    # Requirement metadata
    requirement_id = "ACC-REQ-003"
    D_default = 10.0          # meters
    T_gap = 1.4               # seconds

    # Stimulus definition
    sample_time = 0.1         # seconds
    duration = 1.0            # seconds
    v_set = 20.0              # m/s (steady‑state speed)

    # Time vector
    time_steps = int(np.round(duration / sample_time)) + 1
    time = (np.arange(time_steps) * sample_time).tolist()

    # Instantiate models
    acc = ACCController(sample_time, dtype=dtype)
    plant = PlantModel(sample_time)

    # Initialise signals lists
    v_ego_hist = []
    v_lead_hist = []
    d_actual_hist = []
    a_cmd_hist = []
    mode_hist = []
    d_safe_hist = []

    # Initial conditions (steady‑state)
    v_ego = v_set
    v_lead = v_set
    d_actual = D_default + T_gap * v_ego  # expected safe distance at start
    a_cmd = 0.0
    mode = 0

    # Record initial state
    v_ego_hist.append(v_ego)
    v_lead_hist.append(v_lead)
    d_actual_hist.append(d_actual)
    a_cmd_hist.append(a_cmd)
    mode_hist.append(mode)
    d_safe_hist.append(D_default + T_gap * v_ego)

    # Simulation loop
    for _ in range(1, time_steps):
        # ACC controller computes command based on current measurements
        a_cmd, mode = acc.step(v_ego, v_lead, d_actual, v_set)

        # Plant updates vehicle states
        v_ego, _, d_actual, v_lead = plant.step(a_cmd, v_lead)

        # Record signals
        v_ego_hist.append(v_ego)
        v_lead_hist.append(v_lead)
        d_actual_hist.append(d_actual)
        a_cmd_hist.append(a_cmd)
        mode_hist.append(mode)
        d_safe_hist.append(D_default + T_gap * v_ego)

    # Assemble signals dictionary for oracle evaluation
    signals = {
        'time': time,
        'v_ego': v_ego_hist,
        'v_lead': v_lead_hist,
        'd_actual': d_actual_hist,
        'a_cmd': a_cmd_hist,
        'mode': mode_hist,
        'd_safe': d_safe_hist,
    }

    # Oracle definition (tolerance band on d_safe over the whole window)
    oracle = {
        'type': 'tolerance_band',
        'signal': 'd_safe',
        'tolerance': 0.1,               # meters
        'window': [0.0, duration],      # seconds
    }

    # Evaluate requirement
    passed = evaluate_oracle(oracle, signals)

    details = (
        f"Computed D_safe = {D_default} + {T_gap}*V_ego. "
        f"Tolerance band ±0.1 m over [{oracle['window'][0]}, {oracle['window'][1]}] s."
    )

    return {
        'requirement_id': requirement_id,
        'passed': passed,
        'signals': signals,
        'details': details,
    }