"""
Auto-generated MIL test for ACC-REQ-004
Generated by: src/genai/test_generator_mil.py
"""
import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).resolve().parents[2]))

import numpy as np
from src.models.acc_controller import ACCController
from src.models.plant_model import PlantModel
from src.utils.signal_metrics import evaluate_oracle

def run_acc_req_004(dtype='float64') -> dict:
    import numpy as np
    from src.models.acc_controller import ACCController
    from src.models.plant_model import PlantModel
    from src.utils.signal_metrics import evaluate_oracle

    requirement_id = "ACC-REQ-004"
    sample_time = 0.1
    duration = 5.0
    steps = int(duration / sample_time) + 1

    # Initial steady‑state conditions
    v_ego = 20.0          # m/s
    v_lead = 25.0         # m/s
    d_actual = 30.0       # m
    v_set = 22.0          # m/s (desired speed)

    ctrl = ACCController(sample_time, dtype=dtype)
    plant = PlantModel(sample_time)

    time = []
    v_ego_hist = []
    v_lead_hist = []
    d_actual_hist = []
    a_cmd_hist = []
    mode_hist = []
    d_safe_hist = []

    for i in range(steps):
        t = i * sample_time
        time.append(t)

        # Controller computes acceleration command and mode
        a_cmd, mode = ctrl.step(v_ego, v_lead, d_actual, v_set)

        # Plant updates ego state based on command and lead vehicle dynamics
        v_ego, x_ego, d_actual, v_lead = plant.step(a_cmd, v_lead)

        # Record signals
        v_ego_hist.append(v_ego)
        v_lead_hist.append(v_lead)
        d_actual_hist.append(d_actual)
        a_cmd_hist.append(a_cmd)
        mode_hist.append(mode)

        # Simple safe‑distance estimate (e.g., 2‑second rule) for completeness
        d_safe = max(0.0, v_ego * 2.0)
        d_safe_hist.append(d_safe)

    signals = {
        'time': time,
        'v_ego': v_ego_hist,
        'v_lead': v_lead_hist,
        'd_actual': d_actual_hist,
        'a_cmd': a_cmd_hist,
        'mode': mode_hist,
        'd_safe': d_safe_hist,
    }

    oracle = {
        'type': 'tolerance_band',
        'evaluation_window_s': [0, 5],
        'signal': 'a_cmd',
        'min_value': -3.0,
        'max_value': 2.0,
    }

    passed = evaluate_oracle(oracle, signals)

    details = (
        f"Ego acceleration command remained within the required bounds "
        f"[{oracle['min_value']}, {oracle['max_value']}] m/s²."
    )

    return {
        'requirement_id': requirement_id,
        'passed': passed,
        'signals': signals,
        'details': details,
    }