"""
Auto-generated MIL test for ACC-REQ-001
Generated by: src/genai/test_generator_mil.py
"""
import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).resolve().parents[2]))

import numpy as np
from src.models.acc_controller import ACCController
from src.models.plant_model import PlantModel
from src.utils.signal_metrics import evaluate_oracle

def run_acc_req_001(dtype='float64') -> dict:
    import numpy as np
    from src.models.acc_controller import ACCController
    from src.models.plant_model import PlantModel
    from src.utils.signal_metrics import evaluate_oracle

    # ----------------------------------------------------------------------
    # Simulation configuration (derived from the test intent)
    # ----------------------------------------------------------------------
    sample_time_s = 0.1
    duration_s = 10.0
    steps = int(duration_s / sample_time_s) + 1

    # Stimulus parameters
    v_set = 20.0                     # driver‑set speed (m/s)
    v_lead_initial = 30.0            # lead vehicle faster than set speed (m/s)
    d_initial = 200.0                # large initial gap to emulate absent lead (m)

    # ----------------------------------------------------------------------
    # Instantiate DUT (controller) and plant model
    # ----------------------------------------------------------------------
    controller = ACCController(sample_time_s, dtype=dtype)
    plant = PlantModel(sample_time_s)

    # ----------------------------------------------------------------------
    # Containers for recorded signals
    # ----------------------------------------------------------------------
    time = []
    v_ego_hist = []
    v_lead_hist = []
    d_actual_hist = []
    a_cmd_hist = []
    mode_hist = []
    d_safe_hist = []   # placeholder – will be filled with a simple gap estimate

    # Initial states
    v_ego = 0.0
    v_lead = v_lead_initial
    d_actual = d_initial

    # ----------------------------------------------------------------------
    # Simulation loop
    # ----------------------------------------------------------------------
    for i in range(steps):
        t = i * sample_time_s
        time.append(t)

        # Controller computes acceleration command and mode
        a_cmd, mode = controller.step(v_ego, v_lead, d_actual, v_set)

        # Plant updates ego dynamics and relative distance
        v_ego, x_ego, d_actual, v_lead = plant.step(a_cmd, v_lead)

        # Record signals
        v_ego_hist.append(float(v_ego))
        v_lead_hist.append(float(v_lead))
        d_actual_hist.append(float(d_actual))
        a_cmd_hist.append(float(a_cmd))
        mode_hist.append(int(mode))

        # Simple safe‑distance estimate (time‑gap of 2 s)
        d_safe = float(v_ego) * 2.0
        d_safe_hist.append(d_safe)

    # ----------------------------------------------------------------------
    # Build signals dictionary expected by the oracle evaluator
    # ----------------------------------------------------------------------
    signals = {
        'time': time,
        'v_ego': v_ego_hist,
        'v_lead': v_lead_hist,
        'd_actual': d_actual_hist,
        'a_cmd': a_cmd_hist,
        'mode': mode_hist,
        'd_safe': d_safe_hist,
    }

    # ----------------------------------------------------------------------
    # Oracle definition (tolerance band on v_ego after 5 s)
    # ----------------------------------------------------------------------
    oracle = {
        'type': 'tolerance_band',
        'evaluation_window_s': [5.0, 10.0],
        'signal': 'v_ego',
        'tolerance_mps': 0.5,
        'reference': v_set,
    }

    # ----------------------------------------------------------------------
    # Evaluate requirement
    # ----------------------------------------------------------------------
    passed = evaluate_oracle(oracle, signals)

    details = (
        f"ACC-REQ-001 evaluated over {duration_s}s with sample time {sample_time_s}s. "
        f"Ego speed settled to {v_ego_hist[-1]:.2f} m/s (set point {v_set} m/s). "
        f"Requirement {'PASSED' if passed else 'FAILED'}."
    )

    return {
        'requirement_id': 'ACC-REQ-001',
        'passed': bool(passed),
        'signals': signals,
        'details': details,
    }