"""
Auto-generated MIL test for ACC-REQ-004
Generated by: src/genai/test_generator_mil.py
"""
import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).resolve().parents[2]))

import numpy as np
from src.models.acc_controller import ACCController
from src.models.plant_model import PlantModel
from src.utils.signal_metrics import evaluate_oracle

def run_acc_req_004(dtype='float64') -> dict:
    # Requirement metadata
    requirement_id = "ACC-REQ-004"

    # Simulation parameters from stimulus
    duration_s = 5.0
    sample_time_s = 0.1
    times = np.arange(0.0, duration_s + sample_time_s, sample_time_s, dtype=dtype)

    # Initialize controller and plant
    controller = ACCController(sample_time_s, dtype=dtype)
    plant = PlantModel(sample_time_s)

    # Steady‑state stimulus values (chosen reasonable constants)
    v_set = 20.0          # desired speed [m/s]
    v_ego = 20.0          # initial ego speed [m/s]
    v_lead = 20.0         # initial lead speed [m/s]
    d_actual = 30.0       # initial gap [m]

    # Containers for signals
    v_ego_hist = []
    v_lead_hist = []
    d_actual_hist = []
    a_cmd_hist = []
    mode_hist = []
    d_safe_hist = []

    # Run simulation
    for t in times:
        # Controller computes command based on current states
        a_cmd, mode = controller.step(v_ego, v_lead, d_actual, v_set)

        # Plant updates ego state using the command and lead speed
        v_ego, x_ego, d_actual, v_lead = plant.step(a_cmd, v_lead)

        # Simple safe‑distance estimate (placeholder for illustration)
        d_safe = v_ego * 2.0 + 5.0

        # Record signals
        v_ego_hist.append(float(v_ego))
        v_lead_hist.append(float(v_lead))
        d_actual_hist.append(float(d_actual))
        a_cmd_hist.append(float(a_cmd))
        mode_hist.append(int(mode))
        d_safe_hist.append(float(d_safe))

    # Build signals dictionary for oracle evaluation
    signals = {
        'time': times.tolist(),
        'v_ego': v_ego_hist,
        'v_lead': v_lead_hist,
        'd_actual': d_actual_hist,
        'a_cmd': a_cmd_hist,
        'mode': mode_hist,
        'd_safe': d_safe_hist,
    }

    # Oracle definition (lower and upper bound on a_cmd)
    oracle = {
        'type': 'lower_bound',
        'evaluation_window_s': [0.0, duration_s],
        'signal': 'a_cmd',
        'min_value': -3.0,
        'max_value': 2.0,
    }

    # Evaluate requirement
    passed = evaluate_oracle(oracle, signals)

    details = (
        f"Acceleration command bounded between -3 and 2 m/s²: "
        f"{'PASS' if passed else 'FAIL'}."
    )

    return {
        'requirement_id': requirement_id,
        'passed': bool(passed),
        'signals': signals,
        'details': details,
    }