"""
Auto-generated MIL test for ACC-REQ-005
Generated by: src/genai/test_generator_mil.py
"""
import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).resolve().parents[2]))

import numpy as np
from src.models.acc_controller import ACCController
from src.models.plant_model import PlantModel
from src.utils.signal_metrics import evaluate_oracle

def run_acc_req_005(dtype='float64') -> dict:
    import numpy as np
    from src.models.acc_controller import ACCController
    from src.models.plant_model import PlantModel
    from src.utils.signal_metrics import evaluate_oracle

    # Test parameters
    sample_time = 0.1
    total_time = 2.0
    steps = int(total_time / sample_time) + 1

    # Stimulus definition
    v_lead_initial = 20.0          # m/s
    v_lead_final = 5.0             # m/s (target, may not be reached)
    lead_decel = -3.0              # m/s^2
    event_time = 0.5               # s, when deceleration starts
    d_initial = 30.0               # m
    v_ego_initial = 20.0           # m/s (also the set speed)
    v_set = 20.0                   # m/s

    # Helper to compute lead speed at a given time
    def lead_speed(t):
        if t < event_time:
            return v_lead_initial
        # time since deceleration began
        dt = t - event_time
        v = v_lead_initial + lead_decel * dt
        # do not go below the specified final speed
        return max(v, v_lead_final)

    # Containers for signals
    time_hist = []
    v_ego_hist = []
    v_lead_hist = []
    d_actual_hist = []
    a_cmd_hist = []
    mode_hist = []
    d_safe_hist = []

    # Initialise models
    acc = ACCController(sample_time, dtype=dtype)
    plant = PlantModel(sample_time)

    # Initial states
    v_ego = v_ego_initial
    d_actual = d_initial
    v_lead = lead_speed(0.0)

    for i in range(steps):
        t = i * sample_time

        # Record current time
        time_hist.append(t)

        # Controller step
        a_cmd, mode = acc.step(v_ego, v_lead, d_actual, v_set)

        # Record controller outputs
        a_cmd_hist.append(float(a_cmd))
        mode_hist.append(str(mode))

        # Simple safe distance estimate (placeholder)
        d_safe = v_ego * 2.0 + 5.0
        d_safe_hist.append(float(d_safe))

        # Plant step (ego dynamics)
        v_ego_next, x_ego, d_actual_next, _ = plant.step(a_cmd, v_lead)

        # Update lead speed according to the prescribed deceleration profile
        v_lead_next = lead_speed(t + sample_time)

        # Record signals after plant update
        v_ego_hist.append(float(v_ego_next))
        v_lead_hist.append(float(v_lead_next))
        d_actual_hist.append(float(d_actual_next))

        # Prepare for next iteration
        v_ego = v_ego_next
        d_actual = d_actual_next
        v_lead = v_lead_next

    # Build signals dictionary
    signals = {
        'time': time_hist,
        'v_ego': v_ego_hist,
        'v_lead': v_lead_hist,
        'd_actual': d_actual_hist,
        'a_cmd': a_cmd_hist,
        'mode': mode_hist,
        'd_safe': d_safe_hist,
    }

    # Oracle definition (timing constraint on mode change)
    oracle = {
        'type': 'timing_constraint',
        'evaluation_window_s': [0.0, 0.1],
        'signal': 'mode',
        'timing_tolerance_s': 0.0,
        # The evaluation window is interpreted relative to the event time;
        # the harness is expected to align it accordingly.
    }

    # Evaluate requirement
    passed = evaluate_oracle(oracle, signals)

    details = (
        f"ACC-REQ-005 evaluated over {total_time}s with sample time {sample_time}s. "
        f"Mode transition within 0.1 s after lead deceleration event was "
        f"{'successful' if passed else 'unsuccessful'}."
    )

    return {
        'requirement_id': 'ACC-REQ-005',
        'passed': bool(passed),
        'signals': signals,
        'details': details,
    }