"""
Auto-generated MIL test for ACC-REQ-005
Generated by: src/genai/test_generator_mil.py
"""
import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).resolve().parents[2]))

import numpy as np
from src.models.acc_controller import ACCController
from src.models.plant_model import PlantModel
from src.utils.signal_metrics import evaluate_oracle

def run_acc_req_005(dtype='float64') -> dict:
    import numpy as np
    from src.models.acc_controller import ACCController
    from src.models.plant_model import PlantModel
    from src.utils.signal_metrics import evaluate_oracle

    # Requirement metadata
    requirement_id = "ACC-REQ-005"

    # Simulation parameters from stimulus
    Ts = 0.1  # sample time [s]
    total_time = 10.0
    steps = int(total_time / Ts) + 1

    # Stimulus specifics
    v_set = 30.0                     # desired ego speed [m/s]
    v_lead_initial = 30.0            # lead initial speed [m/s]
    v_lead_final = 10.0              # lead final speed (not directly used)
    d_initial = 42.0                 # initial distance [m]
    lead_decel = -4.0                # lead deceleration [m/s^2]
    event_time = 1.0                 # time when deceleration starts [s]

    # Initialize controller and plant
    controller = ACCController(sample_time_s=Ts, dtype=dtype)
    plant = PlantModel(sample_time_s=Ts)

    # Initial states
    v_ego = v_set                     # start ego at set speed
    v_lead = v_lead_initial
    d_actual = d_initial

    # Containers for signals
    time_hist = []
    v_ego_hist = []
    v_lead_hist = []
    d_actual_hist = []
    a_cmd_hist = []
    mode_hist = []
    d_safe_hist = []

    for step in range(steps):
        t = step * Ts
        # Determine lead acceleration (deceleration event)
        a_lead = lead_decel if t >= event_time else 0.0

        # Compute a safe distance (simple time‑gap model, 2 s gap, min 5 m)
        d_safe = max(5.0, v_ego * 2.0)

        # Controller computes command based on current measurements
        a_cmd, mode = controller.step(v_ego, v_lead, d_actual, v_set)

        # Record signals for this sample
        time_hist.append(t)
        v_ego_hist.append(v_ego)
        v_lead_hist.append(v_lead)
        d_actual_hist.append(d_actual)
        a_cmd_hist.append(a_cmd)
        mode_hist.append(mode)
        d_safe_hist.append(d_safe)

        # Plant updates states using the commanded acceleration and lead dynamics
        # Lead vehicle dynamics are injected via its acceleration
        # The PlantModel interface does not accept lead acceleration directly,
        # so we manually integrate the lead speed for the next step.
        v_lead_next = max(0.0, v_lead + a_lead * Ts)

        # Plant step returns updated ego state and the (already updated) lead speed
        v_ego, _, d_actual, v_lead = plant.step(a_cmd, v_lead_next)

        # Ensure the lead speed used for the next iteration matches our manual integration
        v_lead = v_lead_next

    # Assemble signals dictionary for oracle evaluation
    signals = {
        'time': time_hist,
        'v_ego': v_ego_hist,
        'v_lead': v_lead_hist,
        'd_actual': d_actual_hist,
        'a_cmd': a_cmd_hist,
        'mode': mode_hist,
        'd_safe': d_safe_hist,
    }

    # Oracle definition (timing constraint on mode switch)
    oracle = {
        'type': 'timing_constraint',
        'signal': 'mode',
        'evaluation_window_s': [1.0, 5.0],
        'timing_tolerance_s': 0.1,
    }

    # Evaluate the requirement
    passed = evaluate_oracle(oracle, signals)

    details = (
        f"Requirement {requirement_id} evaluated over {total_time}s. "
        f"Mode switch timing constraint {'met' if passed else 'violated'}."
    )

    return {
        'requirement_id': requirement_id,
        'passed': passed,
        'signals': signals,
        'details': details,
    }