"""
Auto-generated MIL test for ACC-REQ-001
Generated by: src/genai/test_generator_mil.py
"""
import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).resolve().parents[2]))

import numpy as np
from src.models.acc_controller import ACCController
from src.models.plant_model import PlantModel
from src.utils.signal_metrics import evaluate_oracle

def run_acc_req_001(dtype='float64') -> dict:
    import numpy as np
    from src.models.acc_controller import ACCController
    from src.models.plant_model import PlantModel
    from src.utils.signal_metrics import evaluate_oracle

    # Test parameters
    requirement_id = "ACC-REQ-001"
    duration_s = 10.0
    sample_time_s = 0.1
    v_set = 20.0                     # driver‑set speed (m/s)
    v_lead_initial = v_set + 5.0     # lead vehicle faster than set speed
    d_initial = 200.0                # large gap to emulate absent lead

    # Time vector
    time = np.arange(0.0, duration_s + sample_time_s, sample_time_s).tolist()

    # Initialise models
    acc = ACCController(sample_time_s, dtype=dtype)
    plant = PlantModel(sample_time_s)

    # Initialise state variables
    v_ego = 0.0
    v_lead = v_lead_initial
    d_actual = d_initial

    # Containers for signals
    v_ego_hist = []
    v_lead_hist = []
    d_actual_hist = []
    a_cmd_hist = []
    mode_hist = []
    d_safe_hist = []

    for _ in time:
        # ACC controller step
        a_cmd, mode = acc.step(v_ego, v_lead, d_actual, v_set)

        # Plant dynamics step
        v_ego, x_ego, d_actual, v_lead = plant.step(a_cmd, v_lead)

        # Simple safe‑distance estimate (used only for reporting)
        d_safe = v_ego * 1.5 + 2.0

        # Record signals
        v_ego_hist.append(float(v_ego))
        v_lead_hist.append(float(v_lead))
        d_actual_hist.append(float(d_actual))
        a_cmd_hist.append(float(a_cmd))
        mode_hist.append(int(mode))
        d_safe_hist.append(float(d_safe))

    # Build signals dictionary expected by the oracle evaluator
    signals = {
        'time': time,
        'v_ego': v_ego_hist,
        'v_lead': v_lead_hist,
        'd_actual': d_actual_hist,
        'a_cmd': a_cmd_hist,
        'mode': mode_hist,
        'd_safe': d_safe_hist,
    }

    # Oracle definition for tolerance band on v_ego after 5 s
    oracle = {
        'type': 'tolerance_band',
        'evaluation_window_s': [5.0, 10.0],
        'signal': 'v_ego',
        'tolerance_mps': 0.5,
        'set_point': v_set,
    }

    # Evaluate requirement
    passed = evaluate_oracle(oracle, signals)

    details = (
        f"Steady‑state speed tracking test: lead vehicle set to {v_lead_initial:.1f} m/s "
        f"(faster than V_set={v_set:.1f} m/s). After 5 s the ego speed should stay within "
        f"±0.5 m/s of V_set. Test {'passed' if passed else 'failed'}."
    )

    return {
        'requirement_id': requirement_id,
        'passed': bool(passed),
        'signals': signals,
        'details': details,
    }