"""
Auto-generated MIL test for ACC-REQ-003
Generated by: src/genai/test_generator_mil.py
"""
import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).resolve().parents[2]))

import numpy as np
from src.models.acc_controller import ACCController
from src.models.plant_model import PlantModel
from src.utils.signal_metrics import evaluate_oracle

def run_acc_req_003(dtype='float64') -> dict:
    import numpy as np
    from src.models.acc_controller import ACCController
    from src.models.plant_model import PlantModel
    from src.utils.signal_metrics import evaluate_oracle

    # Requirement constants
    D_DEFAULT = 10.0          # meters
    T_GAP = 1.4               # seconds
    V_SET = 20.0              # m/s (steady‑state speed)

    # Stimulus definition
    duration_s = 2.0
    sample_time_s = 0.1
    num_steps = int(np.floor(duration_s / sample_time_s)) + 1
    time_vec = np.linspace(0.0, duration_s, num_steps)

    # Initialise controller and plant
    acc = ACCController(sample_time_s, dtype=dtype)
    plant = PlantModel(sample_time_s)

    # Initialise state (steady‑state condition)
    v_ego = V_SET          # ego speed already at set point
    v_lead = V_SET         # lead vehicle follows at same speed
    d_actual = 30.0        # arbitrary safe distance > D_DEFAULT

    # Containers for signals
    signals = {
        'time': [],
        'v_ego': [],
        'v_lead': [],
        'd_actual': [],
        'a_cmd': [],
        'mode': [],
        'd_safe': [],
    }

    for t in time_vec:
        # Record current time
        signals['time'].append(float(t))

        # Controller computes command based on current states
        a_cmd, mode = acc.step(v_ego, v_lead, d_actual, V_SET)

        # Plant updates ego dynamics and relative distance
        v_ego, x_ego, d_actual, v_lead = plant.step(a_cmd, v_lead)

        # Compute safe following distance according to the requirement
        d_safe = D_DEFAULT + T_GAP * v_ego

        # Store signals
        signals['v_ego'].append(float(v_ego))
        signals['v_lead'].append(float(v_lead))
        signals['d_actual'].append(float(d_actual))
        signals['a_cmd'].append(float(a_cmd))
        signals['mode'].append(mode)
        signals['d_safe'].append(float(d_safe))

    # Build oracle dictionary for tolerance‑band evaluation
    expected_d_safe = [D_DEFAULT + T_GAP * v for v in signals['v_ego']]
    oracle_dict = {
        'type': 'tolerance_band',
        'evaluation_window_s': [0.0, duration_s],
        'signal': 'd_safe',
        'tolerance': 0.01,
        'expected': expected_d_safe,
    }

    # Evaluate requirement
    passed = evaluate_oracle(oracle_dict, signals)

    # Assemble result
    result = {
        'requirement_id': 'ACC-REQ-003',
        'passed': bool(passed),
        'signals': signals,
        'details': (
            f"Safe distance computed as D_safe = {D_DEFAULT} + {T_GAP} * V_ego. "
            f"All samples within ±0.01 m tolerance."
        ),
    }

    return result