"""
Auto-generated MIL test for ACC-REQ-002
Generated by: src/genai/test_generator_mil.py
"""
import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).resolve().parents[2]))

import numpy as np
from src.models.acc_controller import ACCController
from src.models.plant_model import PlantModel
from src.utils.signal_metrics import evaluate_oracle

def run_acc_req_002(dtype='float64') -> dict:
    import numpy as np
    from src.models.acc_controller import ACCController
    from src.models.plant_model import PlantModel
    from src.utils.signal_metrics import evaluate_oracle

    # Requirement metadata
    requirement_id = "ACC-REQ-002"

    # Stimulus parameters
    sample_time_s = 0.1
    duration_s = 15.0
    v_set = 30.0                     # m/s desired ego speed
    v_lead_initial = 30.0            # m/s
    v_lead_final = 15.0              # m/s
    d_initial = 45.0                 # m initial gap
    lead_decel = -3.0                # m/s^2 (negative)
    event_time = 2.0                 # s when lead starts decelerating

    # Time vector
    times = np.arange(0.0, duration_s + sample_time_s, sample_time_s)

    # Instantiate models
    acc = ACCController(sample_time_s, dtype=dtype)
    plant = PlantModel(sample_time_s)

    # Initialise state variables
    v_ego = v_set                     # start at set speed
    d_actual = d_initial
    # Lists to collect signals
    v_ego_hist = []
    v_lead_hist = []
    d_actual_hist = []
    a_cmd_hist = []
    mode_hist = []
    d_safe_hist = []

    for t in times:
        # Determine lead vehicle speed profile
        if t < event_time:
            v_lead = v_lead_initial
        else:
            v_lead = v_lead_initial + lead_decel * (t - event_time)
            if v_lead < v_lead_final:
                v_lead = v_lead_final

        # ACC controller computes command
        a_cmd, mode = acc.step(v_ego, v_lead, d_actual, v_set)

        # Plant updates ego dynamics and gap
        v_ego, x_ego, d_actual, _ = plant.step(a_cmd, v_lead)

        # Simple safe distance model: 2‑second headway
        d_safe = max(0.0, v_ego * 2.0)

        # Record signals
        v_ego_hist.append(float(v_ego))
        v_lead_hist.append(float(v_lead))
        d_actual_hist.append(float(d_actual))
        a_cmd_hist.append(float(a_cmd))
        mode_hist.append(int(mode) if not isinstance(mode, np.generic) else int(mode))
        d_safe_hist.append(float(d_safe))

    # Build signals dictionary for oracle evaluation
    signals = {
        'time': times.tolist(),
        'v_ego': v_ego_hist,
        'v_lead': v_lead_hist,
        'd_actual': d_actual_hist,
        'a_cmd': a_cmd_hist,
        'mode': mode_hist,
        'd_safe': d_safe_hist,
    }

    # Oracle definition
    oracle = {
        'type': 'lower_bound',
        'signal': 'd_actual',
        'evaluation_window_s': [5.0, 15.0],
        'reference_signal': 'd_safe',
    }

    # Evaluate requirement
    passed = evaluate_oracle(oracle, signals)

    details = (
        f"Requirement {requirement_id} evaluated over {duration_s}s. "
        f"Safe distance maintained: {'PASS' if passed else 'FAIL'}."
    )

    return {
        'requirement_id': requirement_id,
        'passed': passed,
        'signals': signals,
        'details': details,
    }